### PR TITLE
Feature: Game Config

### PR DESCRIPTION
**Pull request by thadeucity**
Feature to implement the suggestion on issue #32 

A Settings window to manage game options.

So far the only option available is the difficulty selection, but in the future the same menu can be used for other options.

### CODE REVIEW

**Comment by thadeucity** [comment]
Hello Zurda, anything that I can change for this PR?

**Comment by zurda** [comment]
Awesome work @thadeucity 🙌 Really appreciate this idea and implementation 

One tiny comment/ request: if I'm already in a game, and I open the configuration, then I think my choice won't be reflected until the next game (unless I'm missing something). 

I can think of a few solutions for this, off the top of my head:
1. hiding the configuration button while a game is ongoing 
2. resetting an ongoing game when we change our choice or when we open the configuration? 

I'm sure there are other solutions, feel free to resolve this in any way you see fit. 

I hope this makes sense

**Review by zurda — APPROVED** [review]
Awesome work @thadeucity 🙌 Really appreciate this idea and implementation 

One tiny comment/ request: if I'm already in a game, and I open the configuration, then I think my choice won't be reflected until the next game (unless I'm missing something). 

I can think of a few solutions for this, off the top of my head:
1. hiding the configuration button while a game is ongoing 
2. resetting an ongoing game when we change our choice or when we open the configuration? 

I'm sure there are other solutions, feel free to resolve this in any way you see fit. 

I hope this makes sense

**Comment by thadeucity** [comment]
Code updated, thank you for your feedback.

I used the second proposed solution, I believe this one is more user friendly than the first one.

**Pull request merged**
